import{A as h,a as y,i as p}from"./assets/vendor-4eab3bf9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerpolicy&&(n.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?n.credentials="include":t.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(t){if(t.ep)return;t.ep=!0;const n=s(t);fetch(t.href,n)}})();new h(".accordion-container",{showMultiple:!0});let L=async e=>await y.post("https://portfolio-js.b.goit.study/api/requests",e).then(o=>o.data);const m=document.querySelector("#hero-section");function v(){const e=["red","pink","blue","green"];setInterval(function(){m.className="";const s=Math.floor(Math.random()*e.length),i=e[s];m.classList.add(i)},4e3)}v();const u=document.querySelector(".menu-box"),b=document.querySelector(".button-menu"),k=document.querySelector(".button-mob-menu");b.addEventListener("click",function(){u.classList.toggle("visually-hidden")});k.addEventListener("click",function(){u.classList.toggle("visually-hidden")});const f=document.querySelector(".menu-under"),w=document.querySelector(".menu-tablet-deck");w.addEventListener("click",function(){f.classList.toggle("visually-hidden")});document.addEventListener("click",function(e){(e.target.classList.contains("anchor-header-menu")||e.target.classList.contains("order-btn-menu-mob"))&&u.classList.add("visually-hidden")});document.addEventListener("click",function(e){if(e.target.classList.contains("anchor-menu")){e.preventDefault();const o=e.target.getAttribute("href").substring(1);document.getElementById(o).scrollIntoView({behavior:"smooth"}),f.classList.toggle("visually-hidden")}});const E="https://portfolio-js.b.goit.study/api/reviews",S=document.querySelector(".reviews-list");fetch(E).then(e=>{if(!e.ok)throw new Error("Not found");return e.json()}).then(e=>{S.innerHTML=q(e)}).catch(e=>console.log(e));function q(e){return e.map(({_id:o,avatar_url:s,author:i,review:t})=>`
      <li class="reviews-list-item"id="${o}">
                            <img class="item-img "src="${s}" alt="${i}"
                            width="48"
                            height="48"
                            loading="lazy"
                            />
                            <div class="opinion">
                            <h3 class="author">${i}</h3>
                            <p class="review">${t}</p>
                                </div>
                        </li>`).join("")}const l=document.querySelector(".modal-background"),g=document.querySelector(".modal-close"),I=document.querySelector(".modal");g.addEventListener("click",c);function c(e){(e.type==="click"&&e.currentTarget===g||e.keyCode===27||e.type==="click"&&!I.contains(e.target))&&(l.classList.add("visually-hidden"),document.removeEventListener("keydown",c))}const r=document.querySelector(".footer-form"),d=document.querySelector('input[name="email"]');r.addEventListener("submit",M);function M(e){e.preventDefault();const o=e.target.email.value.trim(),s=e.target.comments.value.trim();(o||s)&&L({email:o,comment:s}).then(t=>{r.reset(),l.classList.remove("visually-hidden"),document.addEventListener("keydown",c),l.addEventListener("click",c)}).catch(t=>{p.error({title:"Oops!",message:"Something went wrong",progressBar:!1,position:"topCenter",color:"#1c1d20",messageColor:"#fafafa",titleColor:"#fafafa"})})}d.addEventListener("focus",()=>{r.classList.contains("success-email")&&r.classList.remove("success-email"),r.classList.contains("failed-email")&&r.classList.remove("failed-email")});d.addEventListener("blur",()=>{d.checkValidity()?r.classList.add("success-email"):r.classList.add("failed-email")});
//# sourceMappingURL=commonHelpers.js.map
